### ISSUE TITLE
Guide/sample MD file requires defining a lot of options

### ISSUE THREAD

**Issue by Reinmar** [cksource/docs-builder#14]
Currently they look like this:

```
title: Second Some Guide (Basic Styles)
description: How do create any guide?
isDisqusAvailable: false
category: Basic Styles

---

### Type: Guides
### Category: Basic Styles
```

* Why are there two type of options?
* Why do I have to define `isDisqusAvailable` in every file (it should default to true)?
* We should limit number of things that need to be defined to minimum.

And a bit different, but related topic – the top heading should be h1 or h2. If we need to start from h3, then something's wrong with the page structure.

**Comment by pomek** [comment]
#### Ad 1.

The guide file consists of two elements:

1. Meta data
2. Content

The first one is defined before the separator `---`. The second one is defined after the separator. So:

```
### Type: Guides
### Category: Basic Styles
```

is just the content of guide.

#### Ad. 2

`isDisqusAvailable` can be set on `true` by default. We just need to add this "option" in `parse-meta-data` module.

#### Ad. 3

The "description" option isn't used anywhere, so can be removed.

**Comment by pomek** [comment]
@Reinmar, in order to create a guide file, we need to have two meta-tags:

```yaml
title: A title for the guide
category: Needed for generating menu
```

Below the meta-tags, you have to put 3x dashes `---` and you can write what do you want.

At this moment, the tag `description` isn't used anywhere. I wanted to put a content of this tag for `<meta name="description">` element. The `isDisqusAvailable` flag can be set as `true` by default. 

OTOH, we can consider introducing some JSON configuration for the files. In this way, we avoid having additional meta-tags in guide/sample files. WDYT?

**Comment by Reinmar** [comment]
I reported a new ticket, with more details: https://github.com/cksource/docs-builder/issues/50.
